version: "3.9"

services:
  postgres_db:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env

  nearest-trucks-transportation:
    build:
      dockerfile: ./dockerfile
      context: .
    container_name: nearest-trucks-transportation
    image: nearest-trucks-transportation:latest
    depends_on:
      - postgres_db
    env_file:
      - .env
    command: >
      bash -c "alembic upgrade head | python populating_db.py | uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000

volumes:
  postgres_db:



