"""relationship fix

Revision ID: 4d6883860a40
Revises: 96aa6452942d
Create Date: 2023-05-25 17:32:20.085341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6883860a40'
down_revision = '96aa6452942d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('pickup_location_id', sa.Integer(), nullable=True))
    op.add_column('goods', sa.Column('delivery_location_id', sa.Integer(), nullable=True))
    op.drop_constraint('goods_location_id_fkey', 'goods', type_='foreignkey')
    op.create_foreign_key(None, 'goods', 'location', ['delivery_location_id'], ['id'])
    op.create_foreign_key(None, 'goods', 'location', ['pickup_location_id'], ['id'])
    op.drop_column('goods', 'location_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'goods', type_='foreignkey')
    op.drop_constraint(None, 'goods', type_='foreignkey')
    op.create_foreign_key('goods_location_id_fkey', 'goods', 'location', ['location_id'], ['id'])
    op.drop_column('goods', 'delivery_location_id')
    op.drop_column('goods', 'pickup_location_id')
    # ### end Alembic commands ###
