"""relationship fix 3

Revision ID: d66a741a15b1
Revises: ddd2827d6e78
Create Date: 2023-05-25 17:42:46.788016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66a741a15b1'
down_revision = 'ddd2827d6e78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
