"""relationship fix 2

Revision ID: ddd2827d6e78
Revises: 4d6883860a40
Create Date: 2023-05-25 17:38:41.783011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd2827d6e78'
down_revision = '4d6883860a40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
